lio_state_predictor:
  ros__parameters:
    odometry_topic: "odometry"
    imu_topic: "livox/imu"
    degenerate_score_topic: "degenerate_score"

    control_state_topic: "control_state"
    control_degenerate_score_topic: "control_degenerate_score"
    control_degraded_topic: "control_degraded"

    publish_rate_hz: 200.0
    fixed_predict_ahead_sec: 0.0
    pos_cov_increase_m2_per_s: 0.02
    yaw_cov_increase_rad2_per_s: 0.01
    degeneracy_ratio_threshold: 0.02
