#!/usr/bin/env python3
"""
Convert a Point-LIO PCD file into a black/white Nav2 static occupancy map.
"""

from __future__ import annotations

import argparse
import binascii
import json
import math
import os
import struct
import sys
import zlib
from array import array
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pcd_map_inspector as inspector


FREE_PIXEL = 254
OCCUPIED_PIXEL = 0
DEFAULT_RESOLUTION = 0.05
DEFAULT_Z_MIN = 0.05
DEFAULT_Z_MAX = 2.0
DEFAULT_PADDING_M = 0.0
DEFAULT_MIN_POINTS_PER_CELL = 3
DEFAULT_OCCUPIED_THRESH = 0.65
DEFAULT_FREE_THRESH = 0.196
DEFAULT_IMAGE_FORMAT = "png"
SUPPORTED_IMAGE_FORMATS = ("png", "pgm")


class MapConversionError(RuntimeError):
    """User-facing map conversion failure."""


@dataclass(frozen=True)
class ConversionResult:
    pcd_file: Path
    image_path: Path
    yaml_path: Path
    analysis: inspector.PcdAnalysis
    suggestion: inspector.MapSuggestion
    min_points_per_cell: int
    projected_points: int
    dropped_outside_map: int
    occupied_cells: int
    free_cells: int
    max_points_in_cell: int
    image_format: str

    @property
    def total_cells(self) -> int:
        return self.suggestion.width_px * self.suggestion.height_px

    def to_dict(self) -> dict[str, Any]:
        return {
            "pcd_file": str(self.pcd_file),
            "image_path": str(self.image_path),
            "yaml_path": str(self.yaml_path),
            "pcd": self.analysis.to_dict(),
            "map": self.suggestion.to_dict(),
            "min_points_per_cell": self.min_points_per_cell,
            "projected_points": self.projected_points,
            "dropped_outside_map": self.dropped_outside_map,
            "occupied_cells": self.occupied_cells,
            "free_cells": self.free_cells,
            "total_cells": self.total_cells,
            "max_points_in_cell": self.max_points_in_cell,
            "image_format": self.image_format,
            "pixel_values": {
                "occupied": OCCUPIED_PIXEL,
                "free": FREE_PIXEL,
            },
            "nav2_yaml": {
                "negate": 0,
                "occupied_thresh": DEFAULT_OCCUPIED_THRESH,
                "free_thresh": DEFAULT_FREE_THRESH,
            },
        }


def _format_float(value: float) -> str:
    text = f"{value:.9f}".rstrip("0").rstrip(".")
    return text if text else "0"


def _output_paths(output_prefix: Path, image_format: str) -> tuple[Path, Path]:
    return output_prefix.with_suffix(f".{image_format}"), output_prefix.with_suffix(".yaml")


def _require_positive_finite(value: float, name: str) -> None:
    if value <= 0.0 or not math.isfinite(value):
        raise MapConversionError(f"{name} 必须是正有限数")


def _require_nonnegative_finite(value: float, name: str) -> None:
    if value < 0.0 or not math.isfinite(value):
        raise MapConversionError(f"{name} 必须是非负有限数")


def _passes_z_filter(z: float, z_min: float | None, z_max: float | None) -> bool:
    if z_min is not None and z < z_min:
        return False
    if z_max is not None and z > z_max:
        return False
    return True


def _axis_cell_index(value: float, origin: float, resolution: float, size_px: int) -> int | None:
    raw_index = (value - origin) / resolution
    index = math.floor(raw_index)
    eps = 1e-9
    if index < 0:
        return 0 if raw_index >= -eps else None
    if index >= size_px:
        return size_px - 1 if raw_index <= size_px + eps else None
    return int(index)


def _build_occupancy_pixels(
    counts: array,
    *,
    width_px: int,
    height_px: int,
    min_points_per_cell: int,
) -> tuple[bytearray, int, int]:
    pixels = bytearray([FREE_PIXEL]) * (width_px * height_px)
    occupied_cells = 0
    max_points_in_cell = 0

    for row_from_bottom in range(height_px):
        image_row = height_px - 1 - row_from_bottom
        for col in range(width_px):
            count = counts[row_from_bottom * width_px + col]
            max_points_in_cell = max(max_points_in_cell, count)
            if count >= min_points_per_cell:
                pixels[image_row * width_px + col] = OCCUPIED_PIXEL
                occupied_cells += 1

    return pixels, occupied_cells, max_points_in_cell


def _write_pgm(path: Path, width_px: int, height_px: int, pixels: bytearray) -> None:
    header = f"P5\n# Generated by pcd_to_nav2_map.py\n{width_px} {height_px}\n255\n"
    with path.open("wb") as stream:
        stream.write(header.encode("ascii"))
        stream.write(pixels)


def _png_chunk(chunk_type: bytes, payload: bytes) -> bytes:
    crc = binascii.crc32(chunk_type)
    crc = binascii.crc32(payload, crc) & 0xFFFFFFFF
    return struct.pack(">I", len(payload)) + chunk_type + payload + struct.pack(">I", crc)


def _write_png(path: Path, width_px: int, height_px: int, pixels: bytearray) -> None:
    if len(pixels) != width_px * height_px:
        raise MapConversionError("PNG 像素数量与图片尺寸不一致")

    raw_scanlines = bytearray()
    for row in range(height_px):
        row_start = row * width_px
        raw_scanlines.append(0)
        raw_scanlines.extend(pixels[row_start:row_start + width_px])

    ihdr = struct.pack(">IIBBBBB", width_px, height_px, 8, 0, 0, 0, 0)
    data = (
        b"\x89PNG\r\n\x1a\n"
        + _png_chunk(b"IHDR", ihdr)
        + _png_chunk(b"IDAT", zlib.compress(bytes(raw_scanlines)))
        + _png_chunk(b"IEND", b"")
    )
    path.write_bytes(data)


def _write_image(path: Path, image_format: str, width_px: int, height_px: int, pixels: bytearray) -> None:
    if image_format == "png":
        _write_png(path, width_px, height_px, pixels)
        return
    if image_format == "pgm":
        _write_pgm(path, width_px, height_px, pixels)
        return
    raise MapConversionError(f"不支持的输出图片格式: {image_format}")


def _write_yaml(path: Path, image_path: Path, suggestion: inspector.MapSuggestion) -> None:
    image_value = os.path.relpath(image_path, path.parent)
    image_value = image_value.replace(os.sep, "/")
    origin = suggestion.origin
    path.write_text(
        "\n".join(
            [
                "# 由 rc26_point_lio/scripts/pcd_to_nav2_map.py 根据 Point-LIO PCD 投影生成。",
                "# 默认黑白语义：黑色为占用，白色为空闲；未生成 unknown 灰格。",
                "# 默认图片格式为 PNG；可用 --image-format pgm 显式生成 PGM。",
                "# 当前地图默认剔除了低处地板点和高处天花板点，只作为 Nav2 2D 静态地图输入。",
                f"image: {image_value}",
                f"resolution: {_format_float(suggestion.resolution)}",
                (
                    "origin: "
                    f"[{_format_float(origin[0])}, {_format_float(origin[1])}, {_format_float(origin[2])}]"
                ),
                "negate: 0",
                f"occupied_thresh: {_format_float(DEFAULT_OCCUPIED_THRESH)}",
                f"free_thresh: {_format_float(DEFAULT_FREE_THRESH)}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def _ensure_outputs_can_be_written(paths: tuple[Path, Path], overwrite: bool) -> None:
    existing = [path for path in paths if path.exists()]
    if existing and not overwrite:
        joined = ", ".join(str(path) for path in existing)
        raise MapConversionError(f"输出文件已存在，若要覆盖请加 --overwrite: {joined}")
    for path in paths:
        path.parent.mkdir(parents=True, exist_ok=True)


def convert_pcd_to_nav2_map(
    pcd_file: Path,
    output_prefix: Path,
    *,
    resolution: float = DEFAULT_RESOLUTION,
    z_min: float | None = DEFAULT_Z_MIN,
    z_max: float | None = DEFAULT_Z_MAX,
    padding_m: float = DEFAULT_PADDING_M,
    min_points_per_cell: int = DEFAULT_MIN_POINTS_PER_CELL,
    image_format: str = DEFAULT_IMAGE_FORMAT,
    overwrite: bool = False,
) -> ConversionResult:
    _require_positive_finite(resolution, "--resolution")
    _require_nonnegative_finite(padding_m, "--padding-m")
    if min_points_per_cell <= 0:
        raise MapConversionError("--min-points-per-cell 必须是正整数")
    if z_min is not None and not math.isfinite(z_min):
        raise MapConversionError("--z-min 必须是有限数")
    if z_max is not None and not math.isfinite(z_max):
        raise MapConversionError("--z-max 必须是有限数")
    if z_min is not None and z_max is not None and z_min > z_max:
        raise MapConversionError("--z-min 不能大于 --z-max")
    image_format = image_format.lower()
    if image_format not in SUPPORTED_IMAGE_FORMATS:
        raise MapConversionError(f"--image-format 必须是 {'/'.join(SUPPORTED_IMAGE_FORMATS)}")

    image_path, yaml_path = _output_paths(output_prefix, image_format)
    _ensure_outputs_can_be_written((image_path, yaml_path), overwrite)

    analysis = inspector.analyze_pcd(pcd_file, z_min=z_min, z_max=z_max)
    suggestion = inspector.make_map_suggestion(analysis.bounds, resolution=resolution, padding_m=padding_m)
    width_px = suggestion.width_px
    height_px = suggestion.height_px
    counts = array("I", [0]) * (width_px * height_px)
    projected_points = 0
    dropped_outside_map = 0

    origin_x = suggestion.origin[0]
    origin_y = suggestion.origin[1]
    for record in inspector.iter_pcd_xyz_records(pcd_file, analysis.header):
        if record.status != "ok" or record.x is None or record.y is None or record.z is None:
            continue
        if not _passes_z_filter(record.z, z_min, z_max):
            continue

        col = _axis_cell_index(record.x, origin_x, resolution, width_px)
        row_from_bottom = _axis_cell_index(record.y, origin_y, resolution, height_px)
        if col is None or row_from_bottom is None:
            dropped_outside_map += 1
            continue
        counts[row_from_bottom * width_px + col] += 1
        projected_points += 1

    pixels, occupied_cells, max_points_in_cell = _build_occupancy_pixels(
        counts,
        width_px=width_px,
        height_px=height_px,
        min_points_per_cell=min_points_per_cell,
    )

    _write_image(image_path, image_format, width_px, height_px, pixels)
    _write_yaml(yaml_path, image_path, suggestion)

    return ConversionResult(
        pcd_file=pcd_file,
        image_path=image_path,
        yaml_path=yaml_path,
        analysis=analysis,
        suggestion=suggestion,
        min_points_per_cell=min_points_per_cell,
        projected_points=projected_points,
        dropped_outside_map=dropped_outside_map,
        occupied_cells=occupied_cells,
        free_cells=width_px * height_px - occupied_cells,
        max_points_in_cell=max_points_in_cell,
        image_format=image_format,
    )


def print_report(result: ConversionResult) -> None:
    print("PCD -> Nav2 黑白地图生成完成")
    print("=" * 72)
    print(f"PCD 文件: {result.pcd_file}")
    print(f"输出图片: {result.image_path}")
    print(f"输出 YAML: {result.yaml_path}")
    print(f"resolution: {_format_float(result.suggestion.resolution)} m/px")
    print(
        "origin: "
        f"[{_format_float(result.suggestion.origin[0])}, "
        f"{_format_float(result.suggestion.origin[1])}, "
        f"{_format_float(result.suggestion.origin[2])}]"
    )
    print(f"image size: {result.suggestion.width_px} x {result.suggestion.height_px} px")
    print(f"Z 过滤: [{result.analysis.z_filter[0]}, {result.analysis.z_filter[1]}]")
    print(f"有效 XYZ 点: {result.analysis.valid_xyz_points}")
    print(f"参与投影点: {result.analysis.selected_points}")
    print(f"成功落格点: {result.projected_points}")
    print(f"落在地图外点: {result.dropped_outside_map}")
    print(f"黑格阈值: {result.min_points_per_cell} 点/格")
    print(f"占用格: {result.occupied_cells} / {result.total_cells}")
    print(f"最大单格点数: {result.max_points_in_cell}")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="将 Point-LIO PCD 投影为 Nav2 map_server 可读取的黑白 PNG/PGM + YAML。"
    )
    parser.add_argument("pcd_file", type=Path, help="待转换的 PCD 文件路径")
    parser.add_argument("--output-prefix", required=True, type=Path, help="输出前缀，默认生成 <prefix>.png 和 <prefix>.yaml")
    parser.add_argument("--resolution", type=float, default=DEFAULT_RESOLUTION, help="地图分辨率，默认 0.05 m/px")
    parser.add_argument("--z-min", type=float, default=DEFAULT_Z_MIN, help="只投影 z >= 该值的点，默认 0.05")
    parser.add_argument("--z-max", type=float, default=DEFAULT_Z_MAX, help="只投影 z <= 该值的点，默认 2.0")
    parser.add_argument("--padding-m", type=float, default=DEFAULT_PADDING_M, help="地图边界额外留白，默认 0")
    parser.add_argument(
        "--image-format",
        choices=SUPPORTED_IMAGE_FORMATS,
        default=DEFAULT_IMAGE_FORMAT,
        help="输出图片格式，默认 png；可显式选择 pgm",
    )
    parser.add_argument(
        "--min-points-per-cell",
        type=int,
        default=DEFAULT_MIN_POINTS_PER_CELL,
        help="每格至少多少个过滤后点才标记为占用，默认 3",
    )
    parser.add_argument("--overwrite", action="store_true", help="允许覆盖已有输出文件")
    parser.add_argument("--json", action="store_true", help="输出 JSON 统计报告")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    try:
        result = convert_pcd_to_nav2_map(
            args.pcd_file,
            args.output_prefix,
            resolution=args.resolution,
            z_min=args.z_min,
            z_max=args.z_max,
            padding_m=args.padding_m,
            min_points_per_cell=args.min_points_per_cell,
            image_format=args.image_format,
            overwrite=args.overwrite,
        )
        if args.json:
            print(json.dumps(result.to_dict(), ensure_ascii=False, indent=2))
        else:
            print_report(result)
        return 0
    except (inspector.InspectorError, MapConversionError) as exc:
        if args.json:
            print(json.dumps({"error": str(exc)}, ensure_ascii=False, indent=2), file=sys.stderr)
        else:
            print(f"错误: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
