# Goal
uint8 TARGET_NODE=0
uint8 TARGET_TASK=1
uint8 TARGET_ROUTE=2
uint8 target_type
string target_id
string team
bool allow_replan
---
# Result
bool success
string terminal_node_id
string failure_code
string failure_reason
---
# Feedback
string active_node_id
string active_edge_id
string exec_state
uint32 replan_count
