# Goal
geometry_msgs/PoseStamped start_pose
geometry_msgs/PoseStamped goal_pose
string team
bool allow_replan
---
# Result
bool success
geometry_msgs/PoseStamped projected_start_pose
geometry_msgs/PoseStamped projected_goal_pose
nav_msgs/Path planned_path
string terminal_segment_id
string failure_code
string failure_reason
---
# Feedback
string active_segment_id
string exec_state
uint32 replan_count
