<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rc26_mechanism</name>
  <version>0.1.0</version>
  <description>Lifecycle-based mechanism server for R2</description>
  <maintainer email="potato@todo.todo">potato</maintainer>
  <maintainer email="2220362462@qq.com">DongXuan Chen</maintainer>
  <license>MIT</license>

  <author email="2220362462@qq.com">DongXuan Chen</author>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>rclcpp_components</depend>
  <depend>rc26_interfaces</depend>
  <depend>rc26_serial</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
