<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rc26_xhu_viewer</name>
  <version>0.1.0</version>
  <description>RC26 RViz GUI shell with preset layouts plus optional plugins and web tools.</description>
  <maintainer email="dev@rc2026.com">RC2026</maintainer>
  <maintainer email="2220362462@qq.com">DongXuan Chen</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>qtbase5-dev</build_depend>
  <build_depend>libsqlite3-dev</build_depend>
  <depend>ament_index_cpp</depend>
  <depend>rclcpp</depend>
  <depend>rviz_common</depend>
  <depend>rviz_rendering</depend>
  <depend>rviz_ogre_vendor</depend>
  <depend>pluginlib</depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>grid_map_rviz_plugin</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <test_depend>python3-yaml</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
