joy_node:
  ros__parameters:
    dev: "/dev/input/js0"
    deadzone: 0.05
    autorepeat_rate: 50.0

rc26_telecontrol_dpad:
  ros__parameters:
    v_linear: 0.2
    v_angular: 0.5
    joy_timeout_s: 0.3
    max_accel: 1.5
    max_alpha: 3.0
    stop_repeat_n: 10
    require_deadman: false
    deadman_button: 4
