<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rc26_bringup</name>
  <version>1.0.0</version>
  <description>R2导航系统统一启动包</description>
  <maintainer email="dev@rc2026.com">RC2026</maintainer>
  <maintainer email="2220362462@qq.com">DongXuan Chen</maintainer>
  <license>Apache-2.0</license>

  <author email="2220362462@qq.com">DongXuan Chen</author>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>rclcpp</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>rosbag2_py</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_rviz_plugins</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>
  <exec_depend>nav2_controller</exec_depend>
  <exec_depend>nav2_dwb_controller</exec_depend>
  <exec_depend>nav2_planner</exec_depend>
  <exec_depend>nav2_navfn_planner</exec_depend>
  <exec_depend>nav2_bt_navigator</exec_depend>
  <exec_depend>nav2_behaviors</exec_depend>
  <exec_depend>nav2_waypoint_follower</exec_depend>
  <exec_depend>nav2_velocity_smoother</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <exec_depend>nav2_costmap_2d</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>nav2_smoother</exec_depend>
  <!-- 里程计模块 -->
  <exec_depend>rc26_mid360_driver</exec_depend>
  <exec_depend>rc26_point_lio</exec_depend>
  <exec_depend>rc26_odom_interface</exec_depend>
  <exec_depend>rc26_sensor_scan</exec_depend>
  <exec_depend>rc26_sensor_extrinsics</exec_depend>
  
  <!-- 自定义包 -->
  <exec_depend>rc26_mcu_transport</exec_depend>
  <exec_depend>rc26_localization</exec_depend>
  <exec_depend>rc26_decision</exec_depend>
  <exec_depend>rc26_vision</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
