<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rc26_vision</name>
  <version>0.1.0</version>
  <description>RC2026 视觉推理模块 - YOLO ONNX 推理与深度融合</description>
  <maintainer email="potato@todo.todo">potato</maintainer>
  <maintainer email="2220362462@qq.com">DongXuan Chen</maintainer>
  <license>MIT</license>

  <author email="2220362462@qq.com">DongXuan Chen</author>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>ament_index_cpp</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>image_transport</depend>
  <depend>message_filters</depend>
  <depend>behaviortree_cpp</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>rc26_interfaces</depend>
  <depend>rc26_serial</depend>
  <depend>yaml-cpp</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <depend>opencv4</depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
